captainVersion: 4
networks:
    db:
        driver: bridge
    search:
        driver: bridge
services:
    $$cap_appname-db:
        image: postgres:$$cap_postgres_version
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        restart: unless-stopped
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: $$cap_postgres_password
            POSTGRES_DB: postgres
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        image: moreerp/odoo:$$cap_odoo_version
        depends_on:
            - $$cap_appname-db
        volumes:
            - $$cap_appname-odoo-web-data:/var/lib/odoo
            - $$cap_odoo-config:/etc/odoo
            - /root/odoo/odoo16/odoo16ee:/mnt/odoo16ee
            - /root/odoo/odoo16/extra-addons/custom:/mnt/custom
            - /root/odoo/odoo16/extra-addons/OCA/server-env-16.0:/mnt/server-env-16.0
            - /root/odoo/odoo16/extra-addons/OCA/product-attribute-16.0:/mnt/product-attribute-16.0
            - /root/odoo/odoo16/extra-addons/OCA/partner-contact-16.0:/mnt/partner-contact-16.0
            - /root/odoo/odoo16/extra-addons/OCA/server-auth-16.0:/mnt/server-auth-16.0
            - /root/odoo/odoo16/extra-addons/OCA/server-tools-16.0:/mnt/server-tools-16.0
            - /root/odoo/odoo16/extra-addons/OCA/stock-logistics-workflow-16.0:/mnt/stock-logistics-workflow-16.0
            - /root/odoo/odoo16/extra-addons/OCA/stock-logistics-reporting-16.0:/mnt/stock-logistics-reporting-16.0
            - /root/odoo/odoo16/extra-addons/OCA/account-payment-16.0:/mnt/account-payment-16.0
            - /root/odoo/odoo16/extra-addons/OCA/bank-payment-16.0:/mnt/bank-payment-16.0
            - /root/odoo/odoo16/extra-addons/OCA/sale-reporting-16.0:/mnt/sale-reporting-16.0
            - /root/odoo/odoo16/extra-addons/OCA/reporting-engine-16.0:/mnt/reporting-engine-16.0
            - /root/odoo/odoo16/extra-addons/OCA/account-invoice-reporting-16.0:/mnt/account-invoice-reporting-16.0
            - /root/odoo/odoo16/extra-addons/OCA/sale-workflow-16.0:/mnt/sale-workflow-16.0
            - /root/odoo/odoo16/extra-addons/OCA/server-ux-16.0:/mnt/server-ux-16.0
            - /root/odoo/odoo16/extra-addons/OCA/purchase-workflow-16.0:/mnt/purchase-workflow-16.0
            - /root/odoo/odoo16/extra-addons/OCA/account-invoicing-16.0:/mnt/account-invoicing-16.0
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: $$cap_postgres_password
            HOST: srv-captain--$$cap_appname-db
        caproverExtra:
            containerHttpPort: '8069'
caproverOneClickApp:
    displayName: 'More-ERP Odoo'
    variables:
        - id: $$cap_postgres_version
          label: Postgres Version
          defaultValue: 13
          description: Check out their docker page for the valid tags https://hub.docker.com/r/library/postgres/tags/
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_password
          label: Postgres Password
          defaultValue: odoo
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_odoo_version
          label: Odoo Version
          defaultValue: 16
          description: Check out their docker page for the valid tags https://hub.docker.com/_/odoo?tab=tags or https://hub.docker.com/r/moreerp/odoo/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_odoo-config
          label: Odoo configuration
          defaultValue: '/root/odoo/odoo16/odoo-config'
    instructions:
        start: Odoo is an open source product CRM
        end: Odoo is deployed and the dashboard is available from http://$$cap_appname.$$cap_root_domain.
    isOfficial: true
    description: Odoo, formerly known as OpenERP, is a suite of open-source business apps written in Python and released under the AGPL license.
    documentation: https://hub.docker.com/_/odoo?tab=description
